export const CartConstants = {
    ADD_TO_CART: 'CART_ADD_TO_CART',
    REMOVE_FROM_CART: 'CART_REMOVE_FROM_CART',
    CHANGE_QUANTITY: 'CART_CHANGE_PRODUCT_QUANTITY',
    EMPTY_CART: 'CART_EMPTY_CART'
}