export const ProductConstants = {
    GET_ALL_REQUEST: 'PRODUCT_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'PRODUCT_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'PRODUCT_GET_ALL_FAILURE',

    GET_BY_ID_REQUEST: 'PRODUCT_GET_BY_ID_REQUEST',
    GET_BY_ID_SUCCESS: 'PRODUCT_GET_BY_ID_SUCCESS',
    GET_BY_ID_FAILURE: 'PRODUCT_GET_BY_ID_FAILURE',
}